{% set name = "python-docs-theme" %}
{% set import = "python_docs_theme" %}
{% set version = "2023.3.1" %}
{% set sha256 = "1471f9779da5bba118b5ac64903ad369f525cd23b781122db9d1607a62d15668" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0]|lower }}/{{ name|lower }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - flit-core >=3.7
    - pip
  run:
    - python >={{ python_min }}
    - sphinx >=2.3.1

test:
  requires:
    - python {{ python_min }}
    - pip
  imports:
    - {{ import }}
  commands:
    - pip check

about:
  home: https://github.com/python/python-docs-theme/
  license: PSF-2.0
  license_file: LICENSE
  summary: The Sphinx theme for the CPython docs and related projects
  description: |
    This is the theme for the Python documentation.
    Note that when adopting this theme, you're also borrowing an element of the
    trust and credibility established by the CPython core developers over the years.
    That's fine, and you're welcome to do so for other Python community
    projects if you so choose, but please keep in mind that in doing so you're also
    choosing to accept some of the responsibility for maintaining that collective trust.
  dev_url: https://github.com/python/python-docs-theme/
  doc_url: https://github.com/python/python-docs-theme/blob/main/README.md

extra:
  recipe-maintainers:
    - CAM-Gerlach
